[workspace]
resolver = "3"
members = [
  "hl7",
  "hl7-2",
  "hl7-3",
  "hl7-3-derive",
  "hl7-3-soap",
  "hl7-2-derive",
  "hl7-2-mllp",
  "hl7-2-soap",
  "hl7-2-from-er7-into-json",
  "hl7-2-from-er7-into-xml",
  "hl7-2-from-json-into-er7",
  "hl7-2-from-xml-into-er7",
  "hl7-2-from-xsd-into-json-dictionary",
  "hl7-2-xml-lite-helper",
]
